import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <h1 className={inter.className}>
            Next Data Fetching Methods
          </h1>
        </div>

        <div className={styles.grid}>
          <a
            href="/csr"
            className={styles.card}
            target="self"
          >
            <h2 className={inter.className}>
              CSR <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <b>Client Side Rendering</b><br />
              - Fetch data on the client side<br />
              - Not SEO friendly
            </p>
          </a>

          <a
            href="/ssr"
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              SSR <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <b>Server Side Rendering</b><br />
              - Fetch data on the server side<br />
              - Send the dynamic bundle to the client<br />
              - SEO friendly
            </p>

          </a>

          <a
            href="/ssg"
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              SSG <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <b>Static Site Generation</b><br />
              - Fetch data on the server after a build/rebuild<br />
              - Send the prebuilt-static-bundle to the client<br />
              - Fastest but static - once changed needs a rebuild<br />
              - SEO friendly
            </p>
          </a>

          <a
            href="/isg"
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              ISG <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <b>Incremental Static Generation</b><br />
              - Best of both worlds<br />
              - Statically generate page/data<br />
              - Rebuild page per interval - say 5 mins?<br />
            </p>
          </a>
        </div>


      </main>
    </>
  )
}
