import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div>
          <h1 className={inter.className}>
            Next Data Fetching Methods
          </h1>
        </div>

        <div className={styles.grid}>
          <a
            href=""
            className={styles.card}
            target="self"
          >
            <h2 className={inter.className}>
              CSR <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Client Side Rendering
              <ul>
                <li>Fetch data on the client side</li>
                <li>Not SEO friendly</li>
              </ul>
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              SSR <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Server Side Rendering
              <ul>
                <li>Fetch data on the server side</li>
                <li>Send the dynamic bundle to the client</li>
                <li>SEO friendly</li>
              </ul>
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              SSG <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Static Site Generation
              <ul>
                <li>Fetch data on the server after a build/rebuild</li>
                <li>Send the prebuilt-static-bundle to the client</li>
                <li>Fastest but static - once changed needs a rebuild</li>
                <li>SEO friendly</li>
              </ul>
            </p>
          </a>

          <a
            href=""
            className={styles.card}
            target="self"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              ISG <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Incremental Static Generation              <ul>
                <li>Best of both worlds</li>
                <li>Statically generate page/data</li>
                <li>Rebuild page per interval - say 5 mins?</li>
              </ul>
            </p>
          </a>
        </div>


      </main>
    </>
  )
}
